name: 'Test'
on: [ push, pull_request, workflow_dispatch ]
env:
  FLUTTER_TARGET_VER: '3.7.x'
jobs:
  lint:
    name: 'Static code analysis'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '${{env.FLUTTER_TARGET_VER}}'
        channel: 'stable'
        cache: true
    - run: flutter --version
    - run: flutter pub get
    # Use this commit till there is a new release that uses Node 16
    - uses: invertase/github-action-dart-analyzer@69c46710f2d03703360106dfac29743fcae45ec6
      with:
        fatal-infos: false
        fatal-warnings: true

  test:
    name: 'Unit tests'
    if: '${{false}}'                   # disabled for now
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '${{env.FLUTTER_TARGET_VER}}'
        channel: 'stable'
        cache: true
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
